# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0406\u043c\u2019\u044f'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u041f\u0440\u0456\u0437\u0432\u0438\u0449\u0435'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_image',
            field=models.ImageField(blank=True, upload_to='client/photos/'),
        ),
    ]
