# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someData', '0002_auto_20160227_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
