# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('someData', '0003_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='documents_file',
            field=models.ImageField(upload_to='client/documents/'),
        ),
    ]
